import { CategoryWords } from 'src/models/category-words.interface';

export const mockData: CategoryWords[] = [
  {
    categoryId: 1,
    categoryName: 'Animals',
    englishWords: [
      'Chick',
      'Whale',
      'Pig',
      'Fox',
      'Tiger',
      'Crab',
      'Bull',
      'Hedgehog',
    ],
    russianWords: [
      'Цыпленок',
      'Кит',
      'Свинка',
      'Лиса',
      'Тигр',
      'Краб',
      'Бык',
      'Ёж',
    ],
    images: [
      'assets/images/categories/animals/chick.svg',
      'assets/images/categories/animals/whale.svg',
      'assets/images/categories/animals/pig.svg',
      'assets/images/categories/animals/fox.svg',
      'assets/images/categories/animals/tiger.svg',
      'assets/images/categories/animals/crab.svg',
      'assets/images/categories/animals/bull.svg',
      'assets/images/categories/animals/hedgehog.svg',
    ],
    sounds: [
      'assets/images/categories/animals/sounds/chick.mp3',
      'assets/images/categories/animals/sounds/whale.mp3',
      'assets/images/categories/animals/sounds/pig.mp3',
      'assets/images/categories/animals/sounds/fox.mp3',
      'assets/images/categories/animals/sounds/tiger.mp3',
      'assets/images/categories/animals/sounds/crab.mp3',
      'assets/images/categories/animals/sounds/bull.mp3',
      'assets/images/categories/animals/sounds/hedgehog.mp3',
    ],
  },
  {
    categoryId: 2,
    categoryName: 'Food',
    englishWords: [
      'Apple',
      'Banana',
      'Bread',
      'Cheese',
      'Pumpkin',
      'Tomato',
      'Cabbage',
      'Orange',
    ],
    russianWords: [
      'Яблоко',
      'Банан',
      'Хлеб',
      'Сыр',
      'Тыква',
      'Помидор',
      'Капуста',
      'Апельсин',
    ],
    images: [
      'assets/images/categories/food/apple.svg',
      'assets/images/categories/food/banana.svg',
      'assets/images/categories/food/bread.svg',
      'assets/images/categories/food/cheese.svg',
      'assets/images/categories/food/pumpkin.svg',
      'assets/images/categories/food/tomato.svg',
      'assets/images/categories/food/cabbage.svg',
      'assets/images/categories/food/orange.svg',
    ],
    sounds: [
      'assets/images/categories/food/sounds/apple.mp3',
      'assets/images/categories/food/sounds/banana.mp3',
      'assets/images/categories/food/sounds/bread.mp3',
      'assets/images/categories/food/sounds/cheese.mp3',
      'assets/images/categories/food/sounds/pumpkin.mp3',
      'assets/images/categories/food/sounds/tomato.mp3',
      'assets/images/categories/food/sounds/cabbage.mp3',
      'assets/images/categories/food/sounds/orange.mp3',
    ],
  },
  {
    categoryId: 3,
    categoryName: 'Body',
    englishWords: [
      'Head',
      'Neck',
      'Hand',
      'Nose',
      'Ear',
      'Foot',
      'Hair',
      'Eye',
    ],
    russianWords: [
      'Голова',
      'Шея',
      'Рука',
      'Нос',
      'Ухо',
      'Нога',
      'Волосы',
      'Глаз',
    ],
    images: [
      'assets/images/categories/body/head.svg',
      'assets/images/categories/body/neck.svg',
      'assets/images/categories/body/hand.svg',
      'assets/images/categories/body/nose.svg',
      'assets/images/categories/body/ear.svg',
      'assets/images/categories/body/foot.svg',
      'assets/images/categories/body/hair.svg',
      'assets/images/categories/body/eye.svg',
    ],
    sounds: [
      'assets/images/categories/body/sounds/head.mp3',
      'assets/images/categories/body/sounds/neck.mp3',
      'assets/images/categories/body/sounds/hand.mp3',
      'assets/images/categories/body/sounds/nose.mp3',
      'assets/images/categories/body/sounds/ear.mp3',
      'assets/images/categories/body/sounds/foot.mp3',
      'assets/images/categories/body/sounds/hair.mp3',
      'assets/images/categories/body/sounds/eye.mp3',
    ],
  },
  {
    categoryId: 4,
    categoryName: 'Nature',
    englishWords: [
      'Forest',
      'Beach',
      'Lake',
      'Volcano',
      'Rainbow',
      'Desert',
      'Snow',
      'Mountain',
    ],
    russianWords: [
      'Лес',
      'Пляж',
      'Озеро',
      'Вулкан',
      'Радуга',
      'Пустыня',
      'Снег',
      'Гора',
    ],
    images: [
      'assets/images/categories/nature/forest.svg',
      'assets/images/categories/nature/beach.svg',
      'assets/images/categories/nature/lake.svg',
      'assets/images/categories/nature/volcano.svg',
      'assets/images/categories/nature/rainbow.svg',
      'assets/images/categories/nature/desert.svg',
      'assets/images/categories/nature/snow.svg',
      'assets/images/categories/nature/mountain.svg',
    ],
    sounds: [
      'assets/images/categories/nature/sounds/forest.mp3',
      'assets/images/categories/nature/sounds/beach.mp3',
      'assets/images/categories/nature/sounds/lake.mp3',
      'assets/images/categories/nature/sounds/volcano.mp3',
      'assets/images/categories/nature/sounds/rainbow.mp3',
      'assets/images/categories/nature/sounds/desert.mp3',
      'assets/images/categories/nature/sounds/snow.mp3',
      'assets/images/categories/nature/sounds/mountain.mp3',
    ],
  },
  {
    categoryId: 5,
    categoryName: 'City',
    englishWords: [
      'Bus',
      'Factory',
      'Park',
      'Church',
      'Police',
      'Building',
      'Subway',
      'Taxi',
    ],
    russianWords: [
      'Автобус',
      'Завод',
      'Парк',
      'Церковь',
      'Полиция',
      'Здание',
      'Метро',
      'Такси',
    ],
    images: [
      'assets/images/categories/city/bus.svg',
      'assets/images/categories/city/factory.svg',
      'assets/images/categories/city/park.svg',
      'assets/images/categories/city/church.svg',
      'assets/images/categories/city/police.svg',
      'assets/images/categories/city/building.svg',
      'assets/images/categories/city/subway.svg',
      'assets/images/categories/city/taxi.svg',
    ],
    sounds: [
      'assets/images/categories/city/sounds/bus.mp3',
      'assets/images/categories/city/sounds/factory.mp3',
      'assets/images/categories/city/sounds/park.mp3',
      'assets/images/categories/city/sounds/church.mp3',
      'assets/images/categories/city/sounds/police.mp3',
      'assets/images/categories/city/sounds/building.mp3',
      'assets/images/categories/city/sounds/subway.mp3',
      'assets/images/categories/city/sounds/taxi.mp3',
    ],
  },
  {
    categoryId: 6,
    categoryName: 'Emotions',
    englishWords: [
      'Happy',
      'Confused',
      'Sad',
      'Excited',
      'Anxious',
      'Angry',
      'Scared',
      'Confident',
    ],
    russianWords: [
      'Счастливый',
      'Спутанный',
      'Грустный',
      'Взволнованный',
      'Тревожный',
      'Злой',
      'Напуганный',
      'Уверенный',
    ],
    images: [
      'assets/images/categories/emotions/happy.svg',
      'assets/images/categories/emotions/confused.svg',
      'assets/images/categories/emotions/sad.svg',
      'assets/images/categories/emotions/excited.svg',
      'assets/images/categories/emotions/anxious.svg',
      'assets/images/categories/emotions/angry.svg',
      'assets/images/categories/emotions/scared.svg',
      'assets/images/categories/emotions/confident.svg',
    ],
    sounds: [
      'assets/images/categories/emotions/sounds/happy.mp3',
      'assets/images/categories/emotions/sounds/confused.mp3',
      'assets/images/categories/emotions/sounds/sad.mp3',
      'assets/images/categories/emotions/sounds/excited.mp3',
      'assets/images/categories/emotions/sounds/anxious.mp3',
      'assets/images/categories/emotions/sounds/angry.mp3',
      'assets/images/categories/emotions/sounds/scared.mp3',
      'assets/images/categories/emotions/sounds/confident.mp3',
    ],
  },
  {
    categoryId: 7,
    categoryName: 'Colors',
    englishWords: [
      'White',
      'Yellow',
      'Red',
      'Purple',
      'Blue',
      'Green',
      'Black',
      'Pink',
    ],
    russianWords: [
      'Белый',
      'Желтый',
      'Красный',
      'Фиолетовый',
      'Синий',
      'Зеленый',
      'Черный',
      'Розовый',
    ],
    images: [
      'assets/images/categories/colors/white.svg',
      'assets/images/categories/colors/yellow.svg',
      'assets/images/categories/colors/red.svg',
      'assets/images/categories/colors/purple.svg',
      'assets/images/categories/colors/blue.svg',
      'assets/images/categories/colors/green.svg',
      'assets/images/categories/colors/black.svg',
      'assets/images/categories/colors/pink.svg',
    ],
    sounds: [
      'assets/images/categories/colors/sounds/white.mp3',
      'assets/images/categories/colors/sounds/yellow.mp3',
      'assets/images/categories/colors/sounds/red.mp3',
      'assets/images/categories/colors/sounds/purple.mp3',
      'assets/images/categories/colors/sounds/blue.mp3',
      'assets/images/categories/colors/sounds/green.mp3',
      'assets/images/categories/colors/sounds/black.mp3',
      'assets/images/categories/colors/sounds/pink.mp3',
    ],
  },
  {
    categoryId: 8,
    categoryName: 'Home',
    englishWords: [
      'Mirror',
      'Kitchen',
      'Bed',
      'Door',
      'Fridge',
      'Bath',
      'Couch',
      'Window',
    ],
    russianWords: [
      'Зеркало',
      'Кухня',
      'Кровать',
      'Дверь',
      'Холодильник',
      'Ванна',
      'Диван',
      'Окно',
    ],
    images: [
      'assets/images/categories/home/mirror.svg',
      'assets/images/categories/home/kitchen.svg',
      'assets/images/categories/home/bed.svg',
      'assets/images/categories/home/door.svg',
      'assets/images/categories/home/fridge.svg',
      'assets/images/categories/home/bath.svg',
      'assets/images/categories/home/couch.svg',
      'assets/images/categories/home/window.svg',
    ],
    sounds: [
      'assets/images/categories/home/sounds/mirror.mp3',
      'assets/images/categories/home/sounds/kitchen.mp3',
      'assets/images/categories/home/sounds/bed.mp3',
      'assets/images/categories/home/sounds/door.mp3',
      'assets/images/categories/home/sounds/fridge.mp3',
      'assets/images/categories/home/sounds/bath.mp3',
      'assets/images/categories/home/sounds/couch.mp3',
      'assets/images/categories/home/sounds/window.mp3',
    ],
  },
];
